### ISSUE TITLE
npe occurs when inserting data into db

### ISSUE THREAD

**Issue by longerian** [longerian/RC4A#26]
03-28 07:01:23.130: W/System.err(2271): java.lang.NullPointerException
03-28 07:01:23.141: W/System.err(2271):     at android.database.sqlite.SQLiteStatement.releaseAndUnlock(SQLiteStatement.java:290)
03-28 07:01:23.141: W/System.err(2271):     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:115)
03-28 07:01:23.141: W/System.err(2271):     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1718)
03-28 07:01:23.141: W/System.err(2271):     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1591)
03-28 07:01:23.151: W/System.err(2271):     at org.rubychina.android.database.RCDBResolver.insertNodes(RCDBResolver.java:127)
03-28 07:01:23.151: W/System.err(2271):     at org.rubychina.android.RCService.insertNodes(RCService.java:111)
03-28 07:01:23.151: W/System.err(2271):     at org.rubychina.android.activity.RCActivity$CacheNodesTask.doInBackground(RCActivity.java:155)
03-28 07:01:23.161: W/System.err(2271):     at org.rubychina.android.activity.RCActivity$CacheNodesTask.doInBackground(RCActivity.java:1)
03-28 07:01:23.161: W/System.err(2271):     at android.os.AsyncTask$2.call(AsyncTask.java:264)
03-28 07:01:23.161: W/System.err(2271):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
03-28 07:01:23.161: W/System.err(2271):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
03-28 07:01:23.181: W/System.err(2271):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-28 07:01:23.181: W/System.err(2271):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-28 07:01:23.181: W/System.err(2271):     at java.lang.Thread.run(Thread.java:856)

**Comment by longerian** [comment]
1.synchronized db operation
2.optimized the de operation by converting the whole topics or nodes list into json and inserting them into db at once rather than recording each topic or node as a row in db

3.this bug doesn't occur everytime, let's see whether the measures taken above works.....

**Comment by longerian** [comment]
solved
