### ISSUE TITLE
json conversion error

### ISSUE THREAD

**Issue by longerian** [longerian/RC4A#28]
03-31 05:31:50.218: W/System.err(3434): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
03-31 05:31:50.242: W/System.err(3434):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
03-31 05:31:50.242: W/System.err(3434):     at com.google.gson.Gson.fromJson(Gson.java:755)
03-31 05:31:50.248: W/System.err(3434):     at com.google.gson.Gson.fromJson(Gson.java:721)
03-31 05:31:50.248: W/System.err(3434):     at com.google.gson.Gson.fromJson(Gson.java:670)
03-31 05:31:50.248: W/System.err(3434):     at org.rubychina.android.util.JsonUtil.fromJsonArray(JsonUtil.java:28)
03-31 05:31:50.248: W/System.err(3434):     at org.rubychina.android.database.RCDBResolver.fetchNodes(RCDBResolver.java:143)
03-31 05:31:50.248: W/System.err(3434):     at org.rubychina.android.RCService.fetchNodes(RCService.java:117)
03-31 05:31:50.248: W/System.err(3434):     at org.rubychina.android.activity.RCActivity.initialize(RCActivity.java:100)
03-31 05:31:50.248: W/System.err(3434):     at org.rubychina.android.activity.RCActivity.access$2(RCActivity.java:99)
03-31 05:31:50.258: W/System.err(3434):     at org.rubychina.android.activity.RCActivity$1.onServiceConnected(RCActivity.java:76)
03-31 05:31:50.258: W/System.err(3434):     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1061)
03-31 05:31:50.268: W/System.err(3434):     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1078)
03-31 05:31:50.268: W/System.err(3434):     at android.os.Handler.handleCallback(Handler.java:605)
03-31 05:31:50.268: W/System.err(3434):     at android.os.Handler.dispatchMessage(Handler.java:92)
03-31 05:31:50.268: W/System.err(3434):     at android.os.Looper.loop(Looper.java:137)
03-31 05:31:50.278: W/System.err(3434):     at android.app.ActivityThread.main(ActivityThread.java:4340)
03-31 05:31:50.278: W/System.err(3434):     at java.lang.reflect.Method.invokeNative(Native Method)
03-31 05:31:50.278: W/System.err(3434):     at java.lang.reflect.Method.invoke(Method.java:511)
03-31 05:31:50.278: W/System.err(3434):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
03-31 05:31:50.288: W/System.err(3434):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
03-31 05:31:50.288: W/System.err(3434):     at dalvik.system.NativeStart.main(Native Method)
03-31 05:31:50.288: W/System.err(3434): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
03-31 05:31:50.298: W/System.err(3434):     at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
03-31 05:31:50.308: W/System.err(3434):     at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
03-31 05:31:50.308: W/System.err(3434):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
03-31 05:31:50.308: W/System.err(3434):     ... 20 more
03-31 05:31:50.348: D/gralloc_goldfish(3434): Emulator without GPU emulation detected.
03-31 05:31:50.448: I/ActivityManager(77): Displayed org.rubychina.android/.activity.RCActivity: +1s601ms
03-31 05:31:50.458: V/PhoneStatusBar(145): setLightsOn(true)
03-31 05:31:50.678: W/InputManagerService(77): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@410895b8 (uid=10005 pid=188)
03-31 05:31:51.128: I/ActivityManager(77): START {cmp=org.rubychina.android/.activity.TopicsActivity} from pid 3434
03-31 05:31:51.128: W/WindowManager(77): Failure taking screenshot for (120x180) to layer 21010
03-31 05:31:51.288: D/dalvikvm(3434): GC_CONCURRENT freed 361K, 7% free 7338K/7815K, paused 5ms+4ms
03-31 05:31:51.978: W/System.err(3434): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
03-31 05:31:51.978: W/System.err(3434):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
03-31 05:31:51.978: W/System.err(3434):     at com.google.gson.Gson.fromJson(Gson.java:755)
03-31 05:31:51.988: W/System.err(3434):     at com.google.gson.Gson.fromJson(Gson.java:721)
03-31 05:31:51.988: W/System.err(3434):     at com.google.gson.Gson.fromJson(Gson.java:670)
03-31 05:31:51.988: W/System.err(3434):     at org.rubychina.android.util.JsonUtil.fromJsonArray(JsonUtil.java:28)
03-31 05:31:51.998: W/System.err(3434):     at org.rubychina.android.database.RCDBResolver.fetchTopics(RCDBResolver.java:88)
03-31 05:31:52.008: W/System.err(3434):     at org.rubychina.android.RCService.fetchTopics(RCService.java:136)
03-31 05:31:52.008: W/System.err(3434):     at org.rubychina.android.activity.TopicsActivity.initialize(TopicsActivity.java:111)
03-31 05:31:52.008: W/System.err(3434):     at org.rubychina.android.activity.TopicsActivity.access$2(TopicsActivity.java:110)
03-31 05:31:52.008: W/System.err(3434):     at org.rubychina.android.activity.TopicsActivity$1.onServiceConnected(TopicsActivity.java:91)
03-31 05:31:52.008: W/System.err(3434):     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1061)
03-31 05:31:52.008: W/System.err(3434):     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1078)
03-31 05:31:52.018: W/System.err(3434):     at android.os.Handler.handleCallback(Handler.java:605)
03-31 05:31:52.018: W/System.err(3434):     at android.os.Handler.dispatchMessage(Handler.java:92)
03-31 05:31:52.018: W/System.err(3434):     at android.os.Looper.loop(Looper.java:137)
03-31 05:31:52.018: W/System.err(3434):     at android.app.ActivityThread.main(ActivityThread.java:4340)
03-31 05:31:52.018: W/System.err(3434):     at java.lang.reflect.Method.invokeNative(Native Method)
03-31 05:31:52.018: W/System.err(3434):     at java.lang.reflect.Method.invoke(Method.java:511)
03-31 05:31:52.028: W/System.err(3434):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
03-31 05:31:52.028: W/System.err(3434):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
03-31 05:31:52.038: W/System.err(3434):     at dalvik.system.NativeStart.main(Native Method)
03-31 05:31:52.048: W/System.err(3434): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
03-31 05:31:52.058: W/System.err(3434):     at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
03-31 05:31:52.068: W/System.err(3434):     at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
03-31 05:31:52.078: W/System.err(3434):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
03-31 05:31:52.078: W/System.err(3434):     ... 20 more
03-31 05:31:52.108: I/WindowManager(77): createSurface Window{412f9238 org.rubychina.android/org.rubychina.android.activity.TopicsActivity paused=false}: DRAW NOW PENDING

**Comment by longerian** [comment]
this occurs only when app shutdown by killing its process. if user presses back_key to exit, no errors are thrown out.

**Comment by longerian** [comment]
use Type instead of Class when parsing json array
